CC:=gcc
LIBS=-lexec_files -lfind_files
LIB_PATH=-L/root/lwmgmt/lib
CFLAGS+=-c
TARGET:=lwmgmt
DEPEND:=lwmgmt.o

$(TARGET):$(DEPEND)
	$(CC) $(LIB_PATH) -o $@ $^ $(LIBS)

%.o:%.c
	$(CC) $(CFLAGS) $(LIB_PATH) -o $@ $^ $(LIBS)

.PHONY:clean
clean:
	rm -rf *.o $(TARGET)
	rm -rf lib/exec_files.o
